// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dievdkkjxlybxlfqexdq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpZXZka2tqeGx5YnhsZnFleGRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NzYwMDgsImV4cCI6MjA3MzU1MjAwOH0.g6-NH06kFegxaf9O3y7UVq2m_gySUDlC0nfOHSs2uyc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});